services:
  - type: web
    name: kouhaku-bot
    env: docker
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - requirements.txt
        - bot/
